# Generated by Django 4.2.7 on 2023-11-20 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('harvester', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Projeto',
        ),
    ]
