# Generated by Django 4.2.7 on 2023-11-20 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('synthesis', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Projeto',
        ),
    ]
