# Generated by Django 4.2.7 on 2023-11-20 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('synthesis', '0002_delete_projeto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('poco', models.CharField(max_length=255)),
                ('um', models.CharField(max_length=255)),
                ('link_dados_rto', models.CharField(max_length=255)),
            ],
        ),
    ]
